name: Docker build and push

on:
  workflow_call:
    inputs:
      name:
        required: true
        type: string
      dockerfile: 
        required: true
        type: string
        
env:
  image: ghcr.io/coffeemakingtoaster/water-bottler/${{ inputs.name }}
  dockerfile: ${{ inputs.dockerfile }}

jobs:
 build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.image }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{ inputs.dockerfile }}
          push: true
          labels: ${{ steps.meta.outputs.labels }}
          tags: ${{ env.image }}:latest
